[Interface]
## Local Address : A private IP address for wg0 interface.
Address = 10.20.10.2/24
ListenPort = 33333
DNS = 8.8.8.8

## local client privateky
PrivateKey = 

[Peer]
# remote server public key
PublicKey = 
Endpoint = 3.12.84.127:33333
AllowedIPs = 0.0.0.0/0
